# This file stores configurations for your Shopify app.

scopes = "read_orders"
SHOPIFY_API_KEY="dbeab1c55f0e6f9e2693f4fd2bbaf363"
HOST="https://e7d1-160-242-11-203.ngrok-free.app"
SHOPIFY_API_SECRET="c13179ab1c17869deb9b24ed432bde2c"
SCOPES="read_orders"
PORT="8081"