# This file stores configurations for your Shopify app.

scopes = "read_orders"
SHOPIFY_API_KEY="fb26845c482a6b847e672021da8c185d"
HOST="https://aminfri-xg7jrfaima-uc.a.run.app"
SHOPIFY_API_SECRET="5d19779d86b5fe20cc0ef470e05d21de"
SCOPES="read_orders"
PORT="8081"